name: tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  build_runner: ^2.4.13
  flutter:
    sdk: flutter
  flutter_heatmap_calendar: ^1.0.5
  flutter_slidable: ^3.1.2
  hive_ce: ^2.8.0+3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
